### ISSUE TITLE
Problems installing package

### ISSUE THREAD

**Issue by jhamman** [edjdavid/intake-excel#2]
Hi @edjdavid, thanks for creating and maintaining this package!

We're finding that the current release is not installable:

```shell
$ pip install intake-excel
```
yields:
```python-traceback
Collecting intake-excel
  Downloading intake-excel-0.1.1.tar.gz (21 kB)
    ERROR: Command errored out with exit status 1:
     command: /Users/jhamman/miniforge3/bin/python3.9 -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-install-cjazyx0m/intake-excel_7aad0eba848144b58ba8e278d5be8d14/setup.py'"'"'; __file__='"'"'/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-install-cjazyx0m/intake-excel_7aad0eba848144b58ba8e278d5be8d14/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' egg_info --egg-base /private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-pip-egg-info-a3daxdtg
         cwd: /private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-install-cjazyx0m/intake-excel_7aad0eba848144b58ba8e278d5be8d14/
    Complete output (5 lines):
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/rg/ldwzyzcs071cjc7dt0ysgs780000gn/T/pip-install-cjazyx0m/intake-excel_7aad0eba848144b58ba8e278d5be8d14/setup.py", line 27, in <module>
        long_description=open('README.md').read(),
    FileNotFoundError: [Errno 2] No such file or directory: 'README.md'
    ----------------------------------------
WARNING: Discarding https://files.pythonhosted.org/packages/f1/be/d82ba17f0564714fd6d9db4df4206196e85fcb1d4df8ab96dc3a9e6bda7c/intake-excel-0.1.1.tar.gz#sha256=9963e4c30a90948d925dea28091951cf3c07b646c6ba73b66183d6a7da691920 (from https://pypi.org/simple/intake-excel/). Command errored out with exit status 1: python setup.py egg_info Check the logs for full command output.
ERROR: Could not find a version that satisfies the requirement intake-excel
ERROR: No matching distribution found for intake-excel
```

A seemingly unrelated problem exists with the conda install instructions:

```shell
$ conda install -c edjdavid intake-excel
```
yields:
```
Collecting package metadata (current_repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.
Collecting package metadata (repodata.json): done
Solving environment: failed with initial frozen solve. Retrying with flexible solve.

PackagesNotFoundError: The following packages are not available from current channels:

  - intake-excel

Current channels:

  - https://conda.anaconda.org/conda-forge/osx-arm64
  - https://conda.anaconda.org/conda-forge/noarch
  - https://repo.anaconda.com/pkgs/main/osx-arm64
  - https://repo.anaconda.com/pkgs/main/noarch
  - https://repo.anaconda.com/pkgs/r/osx-arm64
  - https://repo.anaconda.com/pkgs/r/noarch

To search for alternate channels that may provide the conda package you're
looking for, navigate to

    https://anaconda.org

and use the search bar at the top of the page.
```

FWIW, I've found that installing the package from source works fine so, at least for the pypi issue, it seems like you are just missing the README.md file in your distribution.

**Comment by martindurant** [comment]
It seems that intake-excel is not on conda at all. The pip error suggests that MANIFEST does not include the stated readme file. Installing directly from this repo should work, though.

**Comment by jhamman** [comment]
Thanks for merging #3 @edjdavid. Would you mind issuing a new release? BTW, unless I hear objections, I'd like to create a conda-forge recipe for this package.

**Comment by jhamman** [comment]
I now see that you already issued a new release. Unfortunately, it was also missing a few files. I've opened #4 to explicitly add the missing distribution files.

**Comment by edjdavid** [comment]
Merged and updated the pypi package.
Feel free to create a conda-forge recipe, just didn't have time to configure this.
